// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qhse.Api.Data;

#nullable disable

namespace Qhse.Api.Migrations
{
    [DbContext(typeof(QhseDbContext))]
    [Migration("20260516162516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qhse.Api.Domain.Entities.AiAnalysisLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectiveActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("AiAnalysisLogs", (string)null);
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AuditDate")
                        .HasColumnType("date");

                    b.Property<string>("Auditor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Audits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AuditDate = new DateOnly(2025, 5, 15),
                            Auditor = "E. Lambert",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Reference = "ISO 14001 interne",
                            Scope = "Environnement - Marseille",
                            Score = 92,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            AuditDate = new DateOnly(2025, 6, 2),
                            Auditor = "Cabinet Veritas",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Reference = "ISO 45001 - T2",
                            Scope = "Securite - Usine Lyon",
                            Score = 87,
                            Status = "Planned"
                        });
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Incidents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fuite detectee dans la zone de stockage chimique.",
                            IncidentDate = new DateOnly(2025, 5, 14),
                            Reference = "INC-2041",
                            ReportedBy = "M. Dupont",
                            Severity = "Critical",
                            Site = "Usine Lyon",
                            Status = "InProgress",
                            Title = "Fuite chimique zone B"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncidentDate = new DateOnly(2025, 5, 12),
                            Reference = "INC-2040",
                            ReportedBy = "S. Martin",
                            Severity = "Medium",
                            Site = "Entrepot Lille",
                            Status = "Resolved",
                            Title = "Chute de plain-pied entrepot"
                        });
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.NonConformity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("NonConformities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DueDate = new DateOnly(2025, 5, 30),
                            IncidentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Owner = "Resp. HSE",
                            Reference = "NC-511",
                            Severity = "Critical",
                            SourceReference = "INC-2041",
                            Status = "InProgress",
                            Title = "Etiquetage produit chimique manquant"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            AuditId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DueDate = new DateOnly(2025, 6, 15),
                            Owner = "Resp. Environnement",
                            Reference = "NC-510",
                            Severity = "Medium",
                            SourceReference = "ISO 14001 interne",
                            Status = "Open",
                            Title = "Registre des dechets incomplet"
                        });
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUri")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SizeKb")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("UploadedAt")
                        .HasColumnType("date");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Reports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Rapport mensuel HSE - Avril 2025",
                            Reference = "RPT-088",
                            SizeKb = 842,
                            Type = "PDF",
                            UploadedAt = new DateOnly(2025, 5, 2),
                            UploadedBy = "E. Lambert"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Analyse incidents Q1",
                            Reference = "RPT-086",
                            SizeKb = 332,
                            Type = "DOCX",
                            UploadedAt = new DateOnly(2025, 4, 12),
                            UploadedBy = "S. Martin"
                        });
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hazard")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<int>("Likelihood")
                        .HasColumnType("int");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Risks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Category = "Safety",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Hazard = "Exposition produits chimiques",
                            Impact = 5,
                            Likelihood = 4,
                            Mitigation = "EPI, ventilation et formation trimestrielle",
                            Reference = "R-001"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Category = "Environment",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Hazard = "Rejet aqueux hors normes",
                            Impact = 5,
                            Likelihood = 2,
                            Mitigation = "Controle continu et station d'epuration",
                            Reference = "R-003"
                        });
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.NonConformity", b =>
                {
                    b.HasOne("Qhse.Api.Domain.Entities.Audit", "Audit")
                        .WithMany("NonConformities")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Qhse.Api.Domain.Entities.Incident", "Incident")
                        .WithMany("NonConformities")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Audit");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.Audit", b =>
                {
                    b.Navigation("NonConformities");
                });

            modelBuilder.Entity("Qhse.Api.Domain.Entities.Incident", b =>
                {
                    b.Navigation("NonConformities");
                });
#pragma warning restore 612, 618
        }
    }
}
