/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRisksRouteImport } from './routes/_app.risks'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNonconformitiesRouteImport } from './routes/_app.nonconformities'
import { Route as AppIncidentsRouteImport } from './routes/_app.incidents'
import { Route as AppAuditsRouteImport } from './routes/_app.audits'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRisksRoute = AppRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNonconformitiesRoute = AppNonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsRoute = AppAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/audits': typeof AppAuditsRoute
  '/incidents': typeof AppIncidentsRoute
  '/nonconformities': typeof AppNonconformitiesRoute
  '/reports': typeof AppReportsRoute
  '/risks': typeof AppRisksRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/audits': typeof AppAuditsRoute
  '/incidents': typeof AppIncidentsRoute
  '/nonconformities': typeof AppNonconformitiesRoute
  '/reports': typeof AppReportsRoute
  '/risks': typeof AppRisksRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/audits': typeof AppAuditsRoute
  '/_app/incidents': typeof AppIncidentsRoute
  '/_app/nonconformities': typeof AppNonconformitiesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risks': typeof AppRisksRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-assistant'
    | '/audits'
    | '/incidents'
    | '/nonconformities'
    | '/reports'
    | '/risks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai-assistant'
    | '/audits'
    | '/incidents'
    | '/nonconformities'
    | '/reports'
    | '/risks'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/ai-assistant'
    | '/_app/audits'
    | '/_app/incidents'
    | '/_app/nonconformities'
    | '/_app/reports'
    | '/_app/risks'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risks': {
      id: '/_app/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof AppRisksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nonconformities': {
      id: '/_app/nonconformities'
      path: '/nonconformities'
      fullPath: '/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits': {
      id: '/_app/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AppAuditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAuditsRoute: typeof AppAuditsRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRisksRoute: typeof AppRisksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAuditsRoute: AppAuditsRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRisksRoute: AppRisksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
