name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Publish
        run: dotnet publish backend/Qhse.Api/Qhse.Api.csproj -c Release -o ./publish
      
      - name: Zip publish folder
        run: cd publish && zip -r ../publish.zip .
        
      - name: Deploy via ZipDeploy API
        run: |
          TOKEN=$(echo -n '$qhse-api-dev-amine:RlzHpchGRwHcYFgEEuky9id9bxZqlK5E70oCc7Fx2slPnlDzfoJltiNstrtc' | base64 -w 0)
          curl -X POST \
            "https://qhse-api-dev-amine.scm.azurewebsites.net/api/zipdeploy" \
            -H "Authorization: Basic ${TOKEN}" \
            -H "Content-Type: application/zip" \
            --data-binary @publish.zip \
            --fail \
            -v
